name: Docker Workflow

on:
  push:
    branches:
    - main
    - master
    paths:
      - "requirements.txt"
      - "Dockerfile"
      - ".github/workflows/main.yml"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Variables
        run: |
          IMAGE_NAME="data"
          DOCKER_HUB_USERNAME="ucsdipc"
          echo "IMAGE_NAME=$data" >> $GITHUB_ENV
          echo "DOCKER_HUB_USERNAME=$ucsdipc" >> $GITHUB_ENV

      - name: Build Image
        run: |
          docker build --rm --force-rm -t "data" .
          echo -n "Built image size: "
          docker images "$data" --format "{{.Size}}"

      # - name: List Installed Packages
      #   run:  >
      #     docker run --rm "${IMAGE_NAME}"
      #     conda list

      - name: Login to Dockerhub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push to Dockerhub
        run: docker push "ucsdipc/data"
