name: Docker Workflow

on:
  push:
    branches:
    - main
    - master
    paths:
      - "requirements.txt"
      - "Dockerfile"
      - ".github/workflows/main.yml"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Variables
        run: |
          IMAGE_NAME="data"
          DOCKERHUB_USERNAME="ucsdipc"
          echo "IMAGE_NAME=$data" >> $GITHUB_ENV
          echo "DOCKERHUB_USERNAME=$ucsdipc" >> $GITHUB_ENV

      - name: Build Image
        run: |
          docker build --rm --force-rm -t "data" .
          echo -n "Built image size: "
          docker images "$data" --format "{{.Size}}"

      # - name: List Installed Packages
      #   run:  >
      #     docker run --rm "${IMAGE_NAME}"
      #     conda list

      - name: Login to Dockerhub
        run: >
          echo '${{secrets.DOCKER_HUB_PASSWORD}}' | docker login
          -u "ucsdipc" --password-stdin

      - name: Push to Dockerhub
        run: docker push "$data"
